---
AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Nagios Prometheus exporter service for Operations & Reliability, runs on the existing ECS cluster.

Parameters:

  SplunkHecToken:
    Type: String
    Description: Find this at https://financialtimes.splunkcloud.com/en-GB/manager/financial_times_production/http-eventcollector.
    NoEcho: true

  DockerRevision:
    Type: String

  ServiceName:
    Type: String
    Default: "prometheus-nagios-exporter"

  ParentClusterStackName:
    Type: String
    Description: The parent CF stack which contains the ECS cluster definition.

  ServiceHttpPort:
    Description: >
      The port to route http traffic from external sources, via the ALB.
      See https://github.com/Financial-Times/monitoring-aggregation-ecs/blob/master/documentation/SERVICE_DEFINITIONS.md for guidelines
    Type: Number
    Default: 12000

Resources:

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref ServiceName
      ContainerDefinitions:
        - Name: !Sub "${ServiceName}-service"
          Image: !Sub "nexus.in.ft.com:5000/operations-reliability/${ServiceName}:${DockerRevision}"
          Environment:
            - Name: PORT
              Value: !Ref ServiceHttpPort
          PortMappings:
            - ContainerPort: !Ref ServiceHttpPort
          DnsServers:
            - 10.117.104.41
            - 10.118.104.41
          DockerLabels:
            com.ft.service-name: !Sub "${ServiceName}-service"
            com.ft.service-region: !Ref "AWS::Region"
            com.prometheus-ecs-discovery.port: !Ref ServiceHttpPort
          MemoryReservation: 64
          LogConfiguration:
            LogDriver: splunk
            Options:
              splunk-source: !Sub "${ServiceName}-${AWS::Region}.in.ft.com"
              splunk-url: https://http-inputs-financialtimes.splunkcloud.com
              splunk-token: !Ref SplunkHecToken
              splunk-format: json
              splunk-gzip: true
              tag: "{{.ImageName}}/{{.ImageID}}:{{.Name}}/{{.ID}}"
              labels: org.opencontainers.revision,org.opencontainers.created,com.ft.build-number,com.ft.service-name,com.ft.service-region

  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      Cluster:
        Fn::ImportValue: !Sub "${ParentClusterStackName}-Name"
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS"
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroup
          ContainerPort: !Ref ServiceHttpPort
          ContainerName: !Sub "${ServiceName}-service"

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId:
        Fn::ImportValue: !Sub "${ParentClusterStackName}-VPC"
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200
      HealthCheckPath: /__gtg
      HealthCheckIntervalSeconds: 5
      HealthCheckTimeoutSeconds: 3
      HealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 5

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn:
        Fn::ImportValue: !Sub "${ParentClusterStackName}-HTTPS-Listener-Arn"
      # Should be within a 100 width range. See https://github.com/Financial-Times/monitoring-aggregation-ecs/blob/master/documentation/SERVICE_DEFINITIONS.md for guidelines
      Priority: 200
      Conditions:
        - Field: host-header
          Values:
            - !Sub "${ServiceName}.in.ft.com"
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward

  RegionalListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn:
        Fn::ImportValue: !Sub "${ParentClusterStackName}-HTTPS-Listener-Arn"
      # Should be within a 100 width range. See https://github.com/Financial-Times/monitoring-aggregation-ecs/blob/master/documentation/SERVICE_DEFINITIONS.md for guidelines
      Priority: 201
      Conditions:
        - Field: host-header
          Values:
            - !Sub "${ServiceName}-${AWS::Region}.in.ft.com"
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
