version: 2.1
references:
  working_directory: &working_directory
    /go/src/github.com/Financial-Times/prometheus-nagios-exporter

executors:
  golang:
    docker:
      - image: circleci/golang:1.11
    working_directory: *working_directory
  golang-node:
    docker:
      - image: circleci/golang:1.11-node
    working_directory: *working_directory
  python-node:
    docker:
      - image: circleci/python:3.7-node

commands:
  install_dependencies:
    parameters:
      working_directory:
        type: string
        description: 'The working directory containing the golang project, containing the vendor folder and Gopkg.lock lockfile'
    steps:
      - restore_cache:
          key: v1-gopkg-{{ checksum "Gopkg.lock" }}

      - run:
          name: Install dependencies
          command: |
            if [ ! -d  << parameters.working_directory >>/vendor ]; then
                dep ensure
            fi

      - save_cache:
          key: v1-gopkg-{{ checksum "Gopkg.lock" }}
          paths:
            -  << parameters.working_directory >>/vendor

  attach_golang_workspace:
    steps:
      - attach_workspace:
          at: *working_directory

  docker_login:
    steps:
      - run:
          name: Login to the Docker repository
          command: echo "$DOCKER_REGISTRY_PASSWORD" | docker login nexus.in.ft.com:5000 --username "$DOCKER_REGISTRY_USERNAME" --password-stdin

  load_docker_image:
    steps:
      - run:
          name: Load docker images from previous steps
          command: docker load -i "caches/docker-cache-$CIRCLE_SHA1.tar"

jobs:
  install:
    executor: golang
    steps:
      - checkout

      - install_dependencies:
          working_directory: *working_directory

      - persist_to_workspace:
          root: .
          paths:
            - .

  verify:
    executor: golang
    steps:
      - attach_golang_workspace

      - run:
          name: Check the style
          command: make style

      - run:
          name: Vet the code
          command: make vet

      - run:
          name: Test the code
          command: make test-report

      - store_test_results:
          path: test-results

  build-image:
    executor: golang
    steps:
      - setup_remote_docker
      - attach_golang_workspace
      - docker_login

      - run:
          name: Build the exporter Docker image if it does not exist
          command: |
            export IMAGE_TAG="nexus.in.ft.com:5000/operations-reliability/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1"
            docker pull "$IMAGE_TAG" >/dev/null 2>&1 || true
            if $(docker image inspect "$IMAGE_TAG" >/dev/null 2>&1); then
              echo "Skipping build as image exists for git sha \"$CIRCLE_SHA1\""
              docker tag "$IMAGE_TAG" "financial-times/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1"
            else
              echo "Building new docker image"
              make build
            fi
            mkdir -p caches
            docker save -o "caches/docker-cache-$CIRCLE_SHA1.tar" "financial-times/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1"

      - persist_to_workspace:
          root: .
          paths:
            - .

  security:
    executor: golang-node
    steps:
      - setup_remote_docker
      - attach_golang_workspace
      - load_docker_image

      - run:
          name: Check dependencies and docker images for vulnerabilities
          command: make security

  publish-revision:
    executor: golang
    steps:
      - setup_remote_docker
      - attach_golang_workspace
      - load_docker_image
      - docker_login

      - run:
          name: Push the Docker image
          command: DOCKER_TAG="$CIRCLE_SHA1" make publish

  deploy-service:
    executor: python-node
    steps:
      - attach_workspace:
          at: ~/project

      - run:
          name: Install AWS CLI
          command: sudo pip install awscli

      # TODO: add tests for service responsiveness before rolling out multi-region
      - run:
          name: Update cloudformation stack eu-west-1
          command: DOCKER_TAG="$CIRCLE_SHA1" .circleci/do-exclusively.sh --branch $CIRCLE_BRANCH make deploy-stack
          environment:
            AWS_DEFAULT_REGION: eu-west-1

      - run:
          name: Update cloudformation stack us-east-1
          command: DOCKER_TAG="$CIRCLE_SHA1" .circleci/do-exclusively.sh --branch $CIRCLE_BRANCH make deploy-stack
          environment:
            AWS_DEFAULT_REGION: us-east-1

  security-monitor:
    executor: golang-node
    steps:
      - setup_remote_docker
      - attach_golang_workspace
      - load_docker_image

      - run:
          name: Update snyk monitoring
          command: DOCKER_TAG="$CIRCLE_SHA1" make security-monitor

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - install
      - verify:
          requires:
            - install
      - build-image:
          context: monitoring-agg-ecs-prod
          requires:
            - install
      - security:
          context: rel-eng-creds
          requires:
            - install
            - build-image
      - publish-revision:
          context: monitoring-agg-ecs-prod
          requires:
            - verify
            - build-image
            - security
          filters:
            branches:
              only:
                - master
      - deploy-service:
          context: monitoring-agg-ecs-prod
          requires:
            - publish-revision
          filters:
            branches:
              only:
                - master
      - security-monitor:
          context: rel-eng-creds
          requires:
            - deploy-service
          filters:
            branches:
              only:
                - master

experimental:
  notify:
    branches:
      only:
        - master
